export type Macro = {
  name: string;
  trigger: string;
  url: string;
  color: string;
  icon: string;
  iconUrl?: string;
  key?: string;
};

export type BrandPreset = {
  id: string;
  name: string;
  trigger: string;
  aliases: string[];
  color: string;
  directUrl: string;
  marqueeText: string;
  recommendations: string[];
};

export const macros: Macro[] = [
  // Page 1: Daily Core & Productivity
  { name: 'TikTok', trigger: 'tt', url: 'https://tiktok.com', color: '#00F2FE', icon: 'tiktok', key: '1' },
  { name: 'YouTube', trigger: 'yt', url: 'https://youtube.com', color: '#FF0000', icon: 'youtube', key: '2' },
  { name: 'WhatsApp', trigger: 'wa', url: 'https://web.whatsapp.com', color: '#25D366', icon: 'whatsapp', key: '3' },
  { name: 'Drive', trigger: 'drive', url: 'https://drive.google.com', color: '#0F9D58', icon: 'drive', key: '4' },
  { name: 'GitHub', trigger: 'gh', url: 'https://github.com', color: '#181717', icon: 'github', key: '5' },
  { name: 'Gemini', trigger: 'gemini', url: 'https://gemini.google.com', color: '#1C69FF', icon: 'gemini', key: '6' },
  { name: 'ChatGPT', trigger: 'ai', url: 'https://chatgpt.com', color: '#10A37F', icon: 'chatgpt', key: '7' },
  { name: '9Router', trigger: '9r', url: 'http://localhost:20128/dashboard', color: '#6366F1', icon: 'router', key: '8' },

  // Page 2: Social Media, Media & Communication
  { name: 'Instagram', trigger: 'ig', url: 'https://instagram.com', color: '#E4405F', icon: 'instagram', key: 'q' },
  { name: 'Telegram', trigger: 'tg', url: 'https://web.telegram.org', color: '#229ED9', icon: 'telegram', key: 'w' },
  { name: 'Facebook', trigger: 'fb', url: 'https://facebook.com', color: '#1877F2', icon: 'facebook', key: 'e' },
  { name: 'Spotify', trigger: 'sp', url: 'https://open.spotify.com', color: '#1DB954', icon: 'spotify', key: 'r' },
  { name: 'Discord', trigger: 'dc', url: 'https://discord.com/app', color: '#5865F2', icon: 'discord', key: 't' },
  { name: 'Netflix', trigger: 'nf', url: 'https://netflix.com', color: '#E50914', icon: 'netflix', key: 'y' },
  { name: 'Figma', trigger: 'fig', url: 'https://figma.com', color: '#F24E1E', icon: 'figma', key: 'u' },
  { name: 'Itemku', trigger: 'itemku', url: 'https://itemku.com', color: '#FF7A00', icon: 'itemku', key: 'i' },

  // Page 3: Gaming, Discovery, Work & Shopping
  { name: 'Friv', trigger: 'friv', url: 'https://www.friv.com', color: '#8B5CF6', icon: 'friv', key: 'a' },
  { name: 'Poki', trigger: 'poki', url: 'https://poki.com', color: '#38BDF8', icon: 'poki', key: 's' },
  { name: 'Pinterest', trigger: 'pin', url: 'https://pinterest.com', color: '#BD081C', icon: 'pinterest', key: 'd' },
  { name: 'Reddit', trigger: 'r', url: 'https://reddit.com', color: '#FF4500', icon: 'reddit', key: 'f' },
  { name: 'LinkedIn', trigger: 'in', url: 'https://linkedin.com', color: '#0A66C2', icon: 'linkedin', key: 'g' },
  { name: 'Shopee', trigger: 'shopee', url: 'https://shopee.co.id', color: '#EE4D2D', icon: 'shopee', key: 'h' },
];

export const brandPresets: BrandPreset[] = [
  {
    id: 'tiktok',
    name: 'TIKTOK',
    trigger: 'tt',
    aliases: ['tiktok', 'tt', 'tik tok', 'vt'],
    color: '#00F2FE',
    directUrl: 'https://www.tiktok.com/',
    marqueeText: 'TIKTOK',
    recommendations: [
      'tiktok',
      'https://www.tiktok.com/',
      'tiktok web',
      'tiktok trend',
      'tiktok studio',
      'tiktok download',
      'tiktok shop',
    ],
  },
  {
    id: 'youtube',
    name: 'YOUTUBE',
    trigger: 'yt',
    aliases: ['youtube', 'yt', 'you', 'youtub', 'yutub', 'yutube'],
    color: '#FF0000',
    directUrl: 'https://www.youtube.com/',
    marqueeText: 'YOUTUBE',
    recommendations: [
      'youtube',
      'https://www.youtube.com/',
      'youtube music',
      'youtube studio',
      'youtube kids',
      'youtube video',
      'youtube transcript',
    ],
  },
  {
    id: 'spotify',
    name: 'SPOTIFY',
    trigger: 'sp',
    aliases: ['spotify', 'sp', 'spot', 'music', 'song'],
    color: '#1DB954',
    directUrl: 'https://open.spotify.com/',
    marqueeText: 'SPOTIFY',
    recommendations: [
      'spotify',
      'https://open.spotify.com/',
      'spotify web player',
      'spotify premium',
      'spotify for artists',
      'spotify stats',
    ],
  },
  {
    id: 'friv',
    name: 'FRIV GAMES',
    trigger: 'friv',
    aliases: ['friv', 'friv games', 'game friv'],
    color: '#8B5CF6',
    directUrl: 'https://www.friv.com/',
    marqueeText: 'FRIV',
    recommendations: [
      'friv',
      'https://www.friv.com/',
      'friv classic',
      'friv games online',
      'friv 2017',
      'friv old menu',
    ],
  },
  {
    id: 'poki',
    name: 'POKI GAMES',
    trigger: 'poki',
    aliases: ['poki', 'poki games', 'game poki'],
    color: '#38BDF8',
    directUrl: 'https://poki.com/',
    marqueeText: 'POKI',
    recommendations: [
      'poki',
      'https://poki.com/',
      'poki games online',
      'poki subway surfers',
      'poki temple run',
    ],
  },
  {
    id: 'pinterest',
    name: 'PINTEREST',
    trigger: 'pin',
    aliases: ['pinterest', 'pin', 'pinteres'],
    color: '#BD081C',
    directUrl: 'https://www.pinterest.com/',
    marqueeText: 'PINTEREST',
    recommendations: [
      'pinterest',
      'https://www.pinterest.com/',
      'pinterest login',
      'pinterest aesthetic',
      'pinterest wallpaper',
    ],
  },
  {
    id: 'telegram',
    name: 'TELEGRAM',
    trigger: 'tg',
    aliases: ['telegram', 'tg', 'tele'],
    color: '#229ED9',
    directUrl: 'https://web.telegram.org/',
    marqueeText: 'TELEGRAM',
    recommendations: [
      'telegram',
      'https://web.telegram.org/',
      'telegram web',
      'telegram desktop',
      'telegram login',
    ],
  },
  {
    id: 'reddit',
    name: 'REDDIT',
    trigger: 'r',
    aliases: ['reddit', 'r', 'red it'],
    color: '#FF4500',
    directUrl: 'https://www.reddit.com/',
    marqueeText: 'REDDIT',
    recommendations: [
      'reddit',
      'https://www.reddit.com/',
      'reddit indonesia',
      'reddit programming',
      'reddit web dev',
    ],
  },
  {
    id: 'linkedin',
    name: 'LINKEDIN',
    trigger: 'in',
    aliases: ['linkedin', 'in', 'linked in'],
    color: '#0A66C2',
    directUrl: 'https://www.linkedin.com/',
    marqueeText: 'LINKEDIN',
    recommendations: [
      'linkedin',
      'https://www.linkedin.com/',
      'linkedin jobs',
      'linkedin login',
      'linkedin learning',
    ],
  },
  {
    id: 'shopee',
    name: 'SHOPEE',
    trigger: 'shopee',
    aliases: ['shopee', 'sopel', 'toko shopee'],
    color: '#EE4D2D',
    directUrl: 'https://shopee.co.id/',
    marqueeText: 'SHOPEE',
    recommendations: [
      'shopee',
      'https://shopee.co.id/',
      'shopee live',
      'shopee pay',
      'shopee affiliate',
    ],
  },
  {
    id: 'figma',
    name: 'FIGMA',
    trigger: 'fig',
    aliases: ['figma', 'fig', 'figjam'],
    color: '#F24E1E',
    directUrl: 'https://www.figma.com/',
    marqueeText: 'FIGMA',
    recommendations: [
      'figma',
      'https://www.figma.com/',
      'figma community',
      'figma plugins',
      'figma templates',
      'figjam',
    ],
  },
  {
    id: 'github',
    name: 'GITHUB',
    trigger: 'gh',
    aliases: ['github', 'gh', 'git', 'github.com'],
    color: '#24292E',
    directUrl: 'https://github.com/',
    marqueeText: 'GITHUB',
    recommendations: [
      'github',
      'https://github.com/',
      'github copilot',
      'github desktop',
      'github status',
      'github trending',
    ],
  },
  {
    id: 'whatsapp',
    name: 'WHATSAPP',
    trigger: 'wa',
    aliases: ['whatsapp', 'wa', 'web.whatsapp', 'wa web'],
    color: '#25D366',
    directUrl: 'https://web.whatsapp.com/',
    marqueeText: 'WHATSAPP',
    recommendations: [
      'whatsapp',
      'https://web.whatsapp.com/',
      'whatsapp web',
      'whatsapp download',
      'whatsapp desktop',
    ],
  },
  {
    id: 'chatgpt',
    name: 'CHATGPT',
    trigger: 'ai',
    aliases: ['chatgpt', 'gpt', 'openai', 'ai', 'chat gpt'],
    color: '#10A37F',
    directUrl: 'https://chatgpt.com/',
    marqueeText: 'CHATGPT',
    recommendations: [
      'chatgpt',
      'https://chatgpt.com/',
      'chatgpt 4o',
      'chatgpt login',
      'openai api',
    ],
  },
  {
    id: 'gemini',
    name: 'GEMINI',
    trigger: 'gemini',
    aliases: ['gemini', 'bard', 'google ai', 'gemini ai'],
    color: '#1C69FF',
    directUrl: 'https://gemini.google.com/',
    marqueeText: 'GEMINI',
    recommendations: [
      'gemini',
      'https://gemini.google.com/',
      'google gemini',
      'gemini pro',
      'gemini advanced',
      'gemini api',
    ],
  },
  {
    id: 'instagram',
    name: 'INSTAGRAM',
    trigger: 'ig',
    aliases: ['instagram', 'ig', 'insta'],
    color: '#E4405F',
    directUrl: 'https://www.instagram.com/',
    marqueeText: 'INSTAGRAM',
    recommendations: [
      'instagram',
      'https://www.instagram.com/',
      'instagram web',
      'instagram reels',
      'instagram login',
    ],
  },
  {
    id: 'facebook',
    name: 'FACEBOOK',
    trigger: 'fb',
    aliases: ['facebook', 'fb', 'face book'],
    color: '#1877F2',
    directUrl: 'https://www.facebook.com/',
    marqueeText: 'FACEBOOK',
    recommendations: [
      'facebook',
      'https://www.facebook.com/',
      'facebook web',
      'facebook marketplace',
      'facebook login',
    ],
  },
  {
    id: 'discord',
    name: 'DISCORD',
    trigger: 'dc',
    aliases: ['discord', 'dc', 'disc'],
    color: '#5865F2',
    directUrl: 'https://discord.com/app',
    marqueeText: 'DISCORD',
    recommendations: [
      'discord',
      'https://discord.com/app',
      'discord web',
      'discord nitro',
      'discord status',
    ],
  },
  {
    id: 'netflix',
    name: 'NETFLIX',
    trigger: 'nf',
    aliases: ['netflix', 'nf', 'net flix'],
    color: '#E50914',
    directUrl: 'https://www.netflix.com/',
    marqueeText: 'NETFLIX',
    recommendations: [
      'netflix',
      'https://www.netflix.com/',
      'netflix login',
      'netflix movies',
      'netflix series',
    ],
  },
  {
    id: 'itemku',
    name: 'ITEMKU',
    trigger: 'itemku',
    aliases: ['itemku', 'item ku', 'itemku.com'],
    color: '#FF7A00',
    directUrl: 'https://itemku.com/',
    marqueeText: 'ITEMKU',
    recommendations: [
      'itemku',
      'https://itemku.com/',
      'itemku topup',
      'itemku voucher',
      'itemku mobile legends',
    ],
  },
];

export const engines = [
  { trigger: 'g', name: 'Google', url: 'https://www.google.com/search?q={query}' },
  { trigger: 'yt', name: 'YouTube', url: 'https://www.youtube.com/results?search_query={query}' },
  { trigger: 'gh', name: 'GitHub', url: 'https://github.com/search?q={query}' },
  { trigger: 'so', name: 'Stack Overflow', url: 'https://stackoverflow.com/search?q={query}' },
];
