export type Macro = {
  name: string;
  trigger: string;
  url: string;
  color: string;
  icon: string;
  iconUrl?: string; // Kept for type compatibility, but unused in rendering
  key?: string;
};

export type BrandPreset = {
  id: string;
  name: string;
  trigger: string;
  aliases: string[];
  color: string;
  directUrl: string;
  marqueeText: string;
  recommendations: string[];
};

export const macros: Macro[] = [
  { name: 'Google', trigger: 'g', url: 'https://google.com', color: '#4285F4', icon: 'google', key: '1' },
  { name: 'YouTube', trigger: 'yt', url: 'https://youtube.com', color: '#FF0000', icon: 'youtube', key: '2' },
  { name: 'WhatsApp', trigger: 'wa', url: 'https://web.whatsapp.com', color: '#25D366', icon: 'whatsapp', key: '3' },
  { name: 'Drive', trigger: 'drive', url: 'https://drive.google.com', color: '#0F9D58', icon: 'drive', key: '4' },
  { name: 'GitHub', trigger: 'gh', url: 'https://github.com', color: '#181717', icon: 'github', key: '5' },
  { name: 'Gemini', trigger: 'gemini', url: 'https://gemini.google.com', color: '#1C69FF', icon: 'gemini', key: '6' },
  { name: 'ChatGPT', trigger: 'ai', url: 'https://chatgpt.com', color: '#10A37F', icon: 'chatgpt', key: '7' },
  { name: '9Router', trigger: '9r', url: 'http://localhost:20128/dashboard', color: '#6366F1', icon: 'router', key: '8' },
  { name: 'Instagram', trigger: 'ig', url: 'https://instagram.com', color: '#E4405F', icon: 'instagram', key: 'q' },
  { name: 'TikTok', trigger: 'tt', url: 'https://tiktok.com', color: '#000000', icon: 'tiktok', key: 'w' },
  { name: 'Facebook', trigger: 'fb', url: 'https://facebook.com', color: '#1877F2', icon: 'facebook', key: 'e' },
  { name: 'Spotify', trigger: 'sp', url: 'https://open.spotify.com', color: '#1DB954', icon: 'spotify', key: 'r' },
  { name: 'Discord', trigger: 'dc', url: 'https://discord.com/app', color: '#5865F2', icon: 'discord', key: 't' },
  { name: 'Netflix', trigger: 'nf', url: 'https://netflix.com', color: '#E50914', icon: 'netflix', key: 'y' },
  { name: 'Itemku', trigger: 'itemku', url: 'https://itemku.com', color: '#FF7A00', icon: 'itemku', key: 'u' },
];

export const brandPresets: BrandPreset[] = [
  {
    id: 'youtube',
    name: 'YOUTUBE',
    trigger: 'yt',
    aliases: ['youtube', 'yt', 'you', 'youtub', 'yutub', 'yutube'],
    color: '#FF0000',
    directUrl: 'https://www.youtube.com/',
    marqueeText: 'YOUTUBE',
    recommendations: [
      'youtube',
      'https://www.youtube.com/',
      'youtube music',
      'youtube music web',
      'youtube studio',
      'youtube kids',
      'youtube video',
      'youtube go',
      'youtube transcript',
    ],
  },
  {
    id: 'spotify',
    name: 'SPOTIFY',
    trigger: 'sp',
    aliases: ['spotify', 'sp', 'spot', 'music', 'song'],
    color: '#1DB954',
    directUrl: 'https://open.spotify.com/',
    marqueeText: 'SPOTIFY',
    recommendations: [
      'spotify',
      'https://open.spotify.com/',
      'spotify download',
      'spotify premium',
      'spotify for artists',
      'spotify careers',
      'spotify web player',
      'spotify support',
      'spotify stats',
      'spotify family plan',
    ],
  },
  {
    id: 'google',
    name: 'GOOGLE',
    trigger: 'g',
    aliases: ['google', 'g', 'goog', 'goglev', 'search'],
    color: '#4285F4',
    directUrl: 'https://www.google.com/',
    marqueeText: 'GOOGLE',
    recommendations: [
      'google',
      'https://www.google.com/',
      'google translate',
      'google maps',
      'google drive',
      'google docs',
      'google flights',
      'google scholar',
      'google finance',
    ],
  },
  {
    id: 'github',
    name: 'GITHUB',
    trigger: 'gh',
    aliases: ['github', 'gh', 'git', 'github.com'],
    color: '#24292E',
    directUrl: 'https://github.com/',
    marqueeText: 'GITHUB',
    recommendations: [
      'github',
      'https://github.com/',
      'github copilot',
      'github desktop',
      'github status',
      'github docs',
      'github gist',
      'github trending',
      'github actions',
    ],
  },
  {
    id: 'whatsapp',
    name: 'WHATSAPP',
    trigger: 'wa',
    aliases: ['whatsapp', 'wa', 'web.whatsapp', 'wa web'],
    color: '#25D366',
    directUrl: 'https://web.whatsapp.com/',
    marqueeText: 'WHATSAPP',
    recommendations: [
      'whatsapp',
      'https://web.whatsapp.com/',
      'whatsapp web',
      'whatsapp download',
      'whatsapp desktop',
      'whatsapp status',
      'whatsapp business',
    ],
  },
  {
    id: 'chatgpt',
    name: 'CHATGPT',
    trigger: 'ai',
    aliases: ['chatgpt', 'gpt', 'openai', 'ai', 'chat gpt'],
    color: '#10A37F',
    directUrl: 'https://chatgpt.com/',
    marqueeText: 'CHATGPT',
    recommendations: [
      'chatgpt',
      'https://chatgpt.com/',
      'chatgpt 4o',
      'chatgpt login',
      'openai api',
      'chatgpt app',
      'chatgpt prompt generator',
    ],
  },
  {
    id: 'gemini',
    name: 'GEMINI',
    trigger: 'gemini',
    aliases: ['gemini', 'bard', 'google ai', 'gemini ai'],
    color: '#1C69FF',
    directUrl: 'https://gemini.google.com/',
    marqueeText: 'GEMINI',
    recommendations: [
      'gemini',
      'https://gemini.google.com/',
      'google gemini',
      'gemini pro',
      'gemini advanced',
      'gemini api',
      'gemini studio',
    ],
  },
  {
    id: 'instagram',
    name: 'INSTAGRAM',
    trigger: 'ig',
    aliases: ['instagram', 'ig', 'insta'],
    color: '#E4405F',
    directUrl: 'https://www.instagram.com/',
    marqueeText: 'INSTAGRAM',
    recommendations: [
      'instagram',
      'https://www.instagram.com/',
      'instagram web',
      'instagram login',
      'instagram reels',
      'instagram story viewer',
    ],
  },
  {
    id: 'tiktok',
    name: 'TIKTOK',
    trigger: 'tt',
    aliases: ['tiktok', 'tt', 'tik tok'],
    color: '#00F2FE',
    directUrl: 'https://www.tiktok.com/',
    marqueeText: 'TIKTOK',
    recommendations: [
      'tiktok',
      'https://www.tiktok.com/',
      'tiktok web',
      'tiktok trend',
      'tiktok studio',
      'tiktok download',
    ],
  },
  {
    id: 'facebook',
    name: 'FACEBOOK',
    trigger: 'fb',
    aliases: ['facebook', 'fb', 'face book'],
    color: '#1877F2',
    directUrl: 'https://www.facebook.com/',
    marqueeText: 'FACEBOOK',
    recommendations: [
      'facebook',
      'https://www.facebook.com/',
      'facebook web',
      'facebook marketplace',
      'facebook login',
      'facebook ads manager',
    ],
  },
  {
    id: 'discord',
    name: 'DISCORD',
    trigger: 'dc',
    aliases: ['discord', 'dc', 'disc'],
    color: '#5865F2',
    directUrl: 'https://discord.com/app',
    marqueeText: 'DISCORD',
    recommendations: [
      'discord',
      'https://discord.com/app',
      'discord web',
      'discord nitro',
      'discord status',
      'discord developer portal',
    ],
  },
  {
    id: 'netflix',
    name: 'NETFLIX',
    trigger: 'nf',
    aliases: ['netflix', 'nf', 'net flix'],
    color: '#E50914',
    directUrl: 'https://www.netflix.com/',
    marqueeText: 'NETFLIX',
    recommendations: [
      'netflix',
      'https://www.netflix.com/',
      'netflix login',
      'netflix movies',
      'netflix series',
    ],
  },
  {
    id: 'itemku',
    name: 'ITEMKU',
    trigger: 'itemku',
    aliases: ['itemku', 'item ku', 'itemku.com'],
    color: '#FF7A00',
    directUrl: 'https://itemku.com/',
    marqueeText: 'ITEMKU',
    recommendations: [
      'itemku',
      'https://itemku.com/',
      'itemku topup',
      'itemku voucher',
      'itemku mobile legends',
      'itemku roblox',
    ],
  },
];

export const engines = [
  { trigger: 'g', name: 'Google', url: 'https://www.google.com/search?q={query}' },
  { trigger: 'yt', name: 'YouTube', url: 'https://www.youtube.com/results?search_query={query}' },
  { trigger: 'gh', name: 'GitHub', url: 'https://github.com/search?q={query}' },
  { trigger: 'so', name: 'Stack Overflow', url: 'https://stackoverflow.com/search?q={query}' },
];

